[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
    Accept-Ranges = "bytes"
